In [31]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
import numpy as np
from numpy import arange
X=np.array([[0.01],[1.01],[2.02],[3.98]])
y=np.array([-5,-0.5,4,13])

 # 岭回归

In [36]:
Ridgeclf = Ridge(alpha=0.1)
Ridgeclf.fit(X, y)

Ridge(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [37]:
Ridgeclf.coef_

array([ 4.48147554])

In [38]:
Ridgeclf.intercept_

-4.989989565297158

In [39]:
Ridgeclf.score(X,y)

0.99982013361538236

# LASSO

In [40]:
Lassoclf = Lasso(alpha=0.0)
Lassoclf.fit(X, y)

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel/__main__.py:2: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  from ipykernel import kernelapp as app
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sklearn/linear_model/coordinate_descent.py:470: UserWarning: Coordinate descent with alpha=0 may lead to unexpected results and is discouraged.
  positive)


Lasso(alpha=0.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [41]:
Lassoclf.coef_

array([ 4.53345938])

In [42]:
Lassoclf.intercept_

-5.0812212182022742

In [43]:
Lassoclf.score(X,y)

0.99995161260922372

In [22]:
## 构造回归数据 ##
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=600, n_informative=2, noise=5)

In [26]:
from sklearn.model_selection import GridSearchCV  
param_test1 ={'alpha':arange(0.0,4.0,0.1)}

In [24]:
arange(0.0,2.0,0.05)

array([ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,
        0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
        0.9 ,  0.95,  1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,
        1.35,  1.4 ,  1.45,  1.5 ,  1.55,  1.6 ,  1.65,  1.7 ,  1.75,
        1.8 ,  1.85,  1.9 ,  1.95])

In [27]:
gsearch0=GridSearchCV(Ridge(),param_grid =param_test1,cv=5)
gsearch0.fit(X,y)  
gsearch0.grid_scores_,gsearch0.best_params_, gsearch0.best_score_

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sklearn/model_selection/_search.py:667: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)


([mean: 0.98402, std: 0.00085, params: {'alpha': 0.0},
  mean: 0.98407, std: 0.00083, params: {'alpha': 0.10000000000000001},
  mean: 0.98411, std: 0.00082, params: {'alpha': 0.20000000000000001},
  mean: 0.98416, std: 0.00080, params: {'alpha': 0.30000000000000004},
  mean: 0.98420, std: 0.00078, params: {'alpha': 0.40000000000000002},
  mean: 0.98423, std: 0.00077, params: {'alpha': 0.5},
  mean: 0.98427, std: 0.00075, params: {'alpha': 0.60000000000000009},
  mean: 0.98430, std: 0.00074, params: {'alpha': 0.70000000000000007},
  mean: 0.98433, std: 0.00073, params: {'alpha': 0.80000000000000004},
  mean: 0.98436, std: 0.00072, params: {'alpha': 0.90000000000000002},
  mean: 0.98438, std: 0.00071, params: {'alpha': 1.0},
  mean: 0.98441, std: 0.00070, params: {'alpha': 1.1000000000000001},
  mean: 0.98443, std: 0.00069, params: {'alpha': 1.2000000000000002},
  mean: 0.98445, std: 0.00068, params: {'alpha': 1.3},
  mean: 0.98446, std: 0.00067, params: {'alpha': 1.4000000000000001},
  

# LASSO

In [28]:
gsearch1=GridSearchCV(Lasso(),param_grid =param_test1,cv=3)
gsearch1.fit(X,y)
gsearch1.grid_scores_,gsearch1.best_params_, gsearch1.best_score_

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sklearn/model_selection/_validation.py:238: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  estimator.fit(X_train, y_train, **fit_params)
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sklearn/linear_model/coordinate_descent.py:470: UserWarning: Coordinate descent with alpha=0 may lead to unexpected results and is discouraged.
  positive)
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/sklearn/model_selection/_validation.py:238: UserWarning: With alpha=0, this algorith

([mean: 0.96377, std: 0.00267, params: {'alpha': 0.0},
  mean: 0.99485, std: 0.00054, params: {'alpha': 0.10000000000000001},
  mean: 0.99552, std: 0.00052, params: {'alpha': 0.20000000000000001},
  mean: 0.99570, std: 0.00050, params: {'alpha': 0.30000000000000004},
  mean: 0.99575, std: 0.00048, params: {'alpha': 0.40000000000000002},
  mean: 0.99574, std: 0.00047, params: {'alpha': 0.5},
  mean: 0.99571, std: 0.00045, params: {'alpha': 0.60000000000000009},
  mean: 0.99567, std: 0.00044, params: {'alpha': 0.70000000000000007},
  mean: 0.99562, std: 0.00044, params: {'alpha': 0.80000000000000004},
  mean: 0.99556, std: 0.00043, params: {'alpha': 0.90000000000000002},
  mean: 0.99549, std: 0.00043, params: {'alpha': 1.0},
  mean: 0.99541, std: 0.00042, params: {'alpha': 1.1000000000000001},
  mean: 0.99532, std: 0.00042, params: {'alpha': 1.2000000000000002},
  mean: 0.99523, std: 0.00041, params: {'alpha': 1.3},
  mean: 0.99513, std: 0.00040, params: {'alpha': 1.4000000000000001},
  

In [44]:
?np.corrcoef

In [46]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]